/*
  # Portfolio Application Database Schema

  ## Overview
  This migration creates the complete database schema for the portfolio application,
  including tables for user profiles, skills, projects, achievements, experience,
  education, testimonials, updates, contact messages, and media storage.

  ## Tables Created
  1. **profiles** - User profile information (linked to auth.users)
     - id (uuid, primary key, references auth.users)
     - full_name (text)
     - avatar_url (text)
     - website (text)
     - updated_at (timestamptz)

  2. **skills** - User skills with descriptions and icons
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - name (text, required)
     - description (text)
     - icon (text)
     - created_at (timestamptz)

  3. **projects** - Portfolio projects
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - title (text, required)
     - slug (text, unique, required)
     - description (text)
     - content (text)
     - project_url (text)
     - github_url (text)
     - image_url (text)
     - created_at (timestamptz)

  4. **achievements** - User achievements and awards
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - title (text, required)
     - slug (text, unique, required)
     - description (text)
     - content (text)
     - date (date)
     - created_at (timestamptz)

  5. **experience** - Work experience entries
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - company_name (text, required)
     - role (text, required)
     - start_date (date)
     - end_date (date)
     - responsibilities (text array)
     - created_at (timestamptz)

  6. **education** - Educational background
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - institution_name (text, required)
     - degree (text)
     - field_of_study (text)
     - start_date (date)
     - end_date (date)
     - created_at (timestamptz)

  7. **testimonials** - Testimonials from clients/colleagues
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - author_name (text, required)
     - author_photo_url (text)
     - quote (text)
     - created_at (timestamptz)

  8. **updates** - Recent updates/news
     - id (bigint, auto-generated)
     - user_id (uuid, references profiles)
     - content (text)
     - created_at (timestamptz)

  9. **contact_messages** - Messages from contact form
     - id (bigint, auto-generated)
     - name (text, required)
     - email (text, required)
     - message (text, required)
     - created_at (timestamptz)

  10. **media** - Media files (images/videos)
      - id (bigint, auto-generated)
      - user_id (uuid, references profiles)
      - file_name (text)
      - file_path (text)
      - file_type (text)
      - project_id (bigint, references projects)
      - achievement_id (bigint, references achievements)
      - created_at (timestamptz)

  ## Security
  - Row Level Security (RLS) enabled on all tables
  - Public read access for portfolio content
  - Authenticated users can only modify their own data
  - Contact messages: anyone can insert, only authenticated users can view
  - Storage buckets for resume and media files with public read access

  ## Storage Buckets
  - **resume**: For storing resume PDFs
  - **media**: For storing project images and videos
*/

-- Users/Profiles Table
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  website text,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Skills Table
create table if not exists skills (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  name text not null,
  description text,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table skills enable row level security;

create policy "Skills are viewable by everyone."
  on skills for select
  using ( true );

create policy "Users can insert their own skills."
  on skills for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own skills."
  on skills for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own skills."
  on skills for delete
  using ( auth.uid() = user_id );

-- Projects Table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  title text not null,
  slug text not null unique,
  description text,
  content text,
  project_url text,
  github_url text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;

create policy "Projects are viewable by everyone."
  on projects for select
  using ( true );

create policy "Users can insert their own projects."
  on projects for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own projects."
  on projects for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own projects."
  on projects for delete
  using ( auth.uid() = user_id );

-- Achievements Table
create table if not exists achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  title text not null,
  slug text not null unique,
  description text,
  content text,
  date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table achievements enable row level security;

create policy "Achievements are viewable by everyone."
  on achievements for select
  using ( true );

create policy "Users can insert their own achievements."
  on achievements for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own achievements."
  on achievements for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own achievements."
  on achievements for delete
  using ( auth.uid() = user_id );

-- Experience Table
create table if not exists experience (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  company_name text not null,
  role text not null,
  start_date date,
  end_date date,
  responsibilities text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table experience enable row level security;

create policy "Experience is viewable by everyone."
  on experience for select
  using ( true );

create policy "Users can insert their own experience."
  on experience for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own experience."
  on experience for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own experience."
  on experience for delete
  using ( auth.uid() = user_id );

-- Education Table
create table if not exists education (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  institution_name text not null,
  degree text,
  field_of_study text,
  start_date date,
  end_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table education enable row level security;

create policy "Education is viewable by everyone."
  on education for select
  using ( true );

create policy "Users can insert their own education."
  on education for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own education."
  on education for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own education."
  on education for delete
  using ( auth.uid() = user_id );

-- Testimonials Table
create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  author_name text not null,
  author_photo_url text,
  quote text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table testimonials enable row level security;

create policy "Testimonials are viewable by everyone."
  on testimonials for select
  using ( true );

create policy "Users can insert their own testimonials."
  on testimonials for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own testimonials."
  on testimonials for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own testimonials."
  on testimonials for delete
  using ( auth.uid() = user_id );

-- Updates Table
create table if not exists updates (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table updates enable row level security;

create policy "Updates are viewable by everyone."
  on updates for select
  using ( true );

create policy "Users can insert their own updates."
  on updates for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own updates."
  on updates for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own updates."
  on updates for delete
  using ( auth.uid() = user_id );

-- Contact Messages Table
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table contact_messages enable row level security;

create policy "Allow contact message inserts."
  on contact_messages for insert
  with check ( true );

create policy "Admin can view contact messages."
  on contact_messages for select
  using ( (select auth.uid()) is not null );

-- Media Table
create table if not exists media (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles not null,
  file_name text,
  file_path text,
  file_type text,
  project_id bigint references projects,
  achievement_id bigint references achievements,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table media enable row level security;

create policy "Media is viewable by everyone."
  on media for select
  using ( true );

create policy "Users can insert their own media."
  on media for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own media."
  on media for delete
  using ( auth.uid() = user_id );

-- Supabase Storage Buckets
do $$
begin
  insert into storage.buckets (id, name, public)
  values ('resume', 'resume', true)
  on conflict (id) do nothing;
  
  insert into storage.buckets (id, name, public)
  values ('media', 'media', true)
  on conflict (id) do nothing;
end $$;

-- Storage policies for resume bucket
do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'storage' 
    and tablename = 'objects' 
    and policyname = 'Resume is publicly accessible.'
  ) then
    create policy "Resume is publicly accessible."
      on storage.objects for select
      using ( bucket_id = 'resume' );
  end if;

  if not exists (
    select 1 from pg_policies 
    where schemaname = 'storage' 
    and tablename = 'objects' 
    and policyname = 'Anyone can upload a resume.'
  ) then
    create policy "Anyone can upload a resume."
      on storage.objects for insert
      with check ( bucket_id = 'resume' );
  end if;
end $$;

-- Storage policies for media bucket
do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'storage' 
    and tablename = 'objects' 
    and policyname = 'Media is publicly accessible.'
  ) then
    create policy "Media is publicly accessible."
      on storage.objects for select
      using ( bucket_id = 'media' );
  end if;

  if not exists (
    select 1 from pg_policies 
    where schemaname = 'storage' 
    and tablename = 'objects' 
    and policyname = 'Anyone can upload media.'
  ) then
    create policy "Anyone can upload media."
      on storage.objects for insert
      with check ( bucket_id = 'media' );
  end if;
end $$;